spring:
      datasource:
        url: jdbc:postgresql://localhost:5432/companies
        username: alan-pl
        password: iledev
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true